apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.appName}}
  name: {{ .Values.serviceName}}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort}}
      protocol: TCP
      targetPort: {{ .Values.targetPort}}
  selector:
    app: {{ .Values.appName}}
  type: NodePort
status:
  loadBalancer: {}
